name = "lustre_portal"
version = "1.0.1"
target = "javascript"

description = "A portal component for Lustre to render children somewhere else in the DOM."
repository = { type = "github", user = "lustre-labs", repo = "portal" }
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
# gleam_stdlib = { path = "../../gleam-lang/stdlib" }
lustre = ">= 5.3.0 and < 6.0.0"
# lustre = { path = "../lustre" }

[dev-dependencies]
esgleam = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
