name = "lustre_portal"
version = "1.0.0"
target = "javascript"

description = "A Portal Web Component for Lustre"
repository = { type = "github", user = "lustre-labs", repo = "portal" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = { git = "https://github.com/lustre-labs/lustre.git", ref = "v5" }
# lustre = { path = "../lustre" }
